<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.16',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'export',
  'published_date' => '2014-10-18 05:01:39',
  'type' => 'module',
  'version' => 1413608499,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'export',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.export.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/language/en_us.lang.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'Accountscasem_c' => 
    array (
      'id' => 'Accountscasem_c',
      'name' => 'casem_c',
      'label' => 'LBL_CASEM',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:53:55',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsclaimfilingstatus_c' => 
    array (
      'id' => 'Accountsclaimfilingstatus_c',
      'name' => 'claimfilingstatus_c',
      'label' => 'LBL_CLAIMFILINGSTATUS',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:55:06',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsclaimstatus_c' => 
    array (
      'id' => 'Accountsclaimstatus_c',
      'name' => 'claimstatus_c',
      'label' => 'LBL_CLAIMSTATUS',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'New',
      'date_modified' => '2014-08-26 15:36:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'claimstatus_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountscompanyname_c' => 
    array (
      'id' => 'Accountscompanyname_c',
      'name' => 'companyname_c',
      'label' => 'LBL_COMPANYNAME',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 23:19:47',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsdram_c' => 
    array (
      'id' => 'Accountsdram_c',
      'name' => 'dram_c',
      'label' => 'LBL_DRAM',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:57:45',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountseggs_c' => 
    array (
      'id' => 'Accountseggs_c',
      'name' => 'eggs_c',
      'label' => 'LBL_EGGS',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:57:53',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsestclaim_c' => 
    array (
      'id' => 'Accountsestclaim_c',
      'name' => 'estclaim_c',
      'label' => 'LBL_ESTCLAIM',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:55:43',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsfirst_name_c' => 
    array (
      'id' => 'Accountsfirst_name_c',
      'name' => 'first_name_c',
      'label' => 'LBL_FIRST_NAME',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 23:17:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsfreightforwarders_c' => 
    array (
      'id' => 'Accountsfreightforwarders_c',
      'name' => 'freightforwarders_c',
      'label' => 'LBL_FREIGHTFORWARDERS',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:57:25',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountslast_name_c' => 
    array (
      'id' => 'Accountslast_name_c',
      'name' => 'last_name_c',
      'label' => 'LBL_LAST_NAME',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 23:17:23',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountslcd_c' => 
    array (
      'id' => 'Accountslcd_c',
      'name' => 'lcd_c',
      'label' => 'LBL_LCD',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:56:57',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsphone_mobile_c' => 
    array (
      'id' => 'Accountsphone_mobile_c',
      'name' => 'phone_mobile_c',
      'label' => 'LBL_PHONE_MOBILE',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 23:17:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsphone_work_c' => 
    array (
      'id' => 'Accountsphone_work_c',
      'name' => 'phone_work_c',
      'label' => 'LBL_PHONE_WORK',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 23:17:49',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsstatements_c' => 
    array (
      'id' => 'Accountsstatements_c',
      'name' => 'statements_c',
      'label' => 'LBL_STATEMENTS',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:54:19',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountstaxid_c' => 
    array (
      'id' => 'Accountstaxid_c',
      'name' => 'taxid_c',
      'label' => 'LBL_TAXID',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:56:19',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsvisa_c' => 
    array (
      'id' => 'Accountsvisa_c',
      'name' => 'visa_c',
      'label' => 'LBL_VISA',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2014-07-31 22:56:48',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/detailviewdefs.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/detailviewdefs.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/editviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/editviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/ru_ru.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/ru_ru.SecurityGroups.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/es_es.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/es_es.SecurityGroups.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/hu_hu.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/hu_hu.SecurityGroups.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/en_us.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/en_us.SecurityGroups.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/ua_ua.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/ua_ua.SecurityGroups.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/de_de.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/de_de.SecurityGroups.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/pt_br.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/pt_br.SecurityGroups.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/it_it.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/it_it.SecurityGroups.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Language/en_us.SendInfopack.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Language/en_us.SendInfopack.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_dram_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_dram_c.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_last_name_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_last_name_c.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_statements_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_statements_c.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_freightforwarders_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_freightforwarders_c.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_claimfilingstatus_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_claimfilingstatus_c.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_claimstatus_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_claimstatus_c.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/pass1_sendinfopack_accounts_Accounts.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/pass1_sendinfopack_accounts_Accounts.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_visa_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_visa_c.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_companyname_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_companyname_c.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_taxid_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_taxid_c.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_eggs_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_eggs_c.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_first_name_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_first_name_c.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_lcd_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_lcd_c.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_phone_work_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_phone_work_c.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_casem_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_casem_c.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_phone_mobile_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_phone_mobile_c.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Vardefs/sugarfield_estclaim_c.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Vardefs/sugarfield_estclaim_c.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/Accounts/Ext/Layoutdefs/pass1_sendinfopack_accounts_Accounts.php',
      'to' => 'custom/Extension/modules/Accounts/Ext/Layoutdefs/pass1_sendinfopack_accounts_Accounts.php',
    ),
  ),
);