<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.16',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'lead',
  'published_date' => '2014-10-20 06:17:08',
  'type' => 'module',
  'version' => 1413785828,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'lead',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.lead.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/language/en_us.lang.php',
      'to_module' => 'Leads',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'Leadsaltsignertitle_c' => 
    array (
      'id' => 'Leadsaltsignertitle_c',
      'name' => 'altsignertitle_c',
      'label' => 'LBL_ALTSIGNERTITLE',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-05-03 11:47:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => '',
    ),
    'Leadscases_c' => 
    array (
      'id' => 'Leadscases_c',
      'name' => 'cases_c',
      'label' => 'LBL_CASES',
      'comments' => '',
      'help' => 'Current Cases',
      'module' => 'Leads',
      'type' => 'multienum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => '^Visa^',
      'date_modified' => '2014-07-29 02:52:55',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '1',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'cases_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '^Visa^',
    ),
    'Leadsclaimfilingnumber_c' => 
    array (
      'id' => 'Leadsclaimfilingnumber_c',
      'name' => 'claimfilingnumber_c',
      'label' => 'LBL_CLAIMFILINGNUMBER',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'New',
      'date_modified' => '2014-09-09 15:20:59',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'claimfilingnumber_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Leadscompanyname_c' => 
    array (
      'id' => 'Leadscompanyname_c',
      'name' => 'companyname_c',
      'label' => 'LBL_COMPANYNAME',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => NULL,
      'date_modified' => '2014-05-03 11:47:14',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => '',
    ),
    'Leadsdbaname_c' => 
    array (
      'id' => 'Leadsdbaname_c',
      'name' => 'dbaname_c',
      'label' => 'LBL_DBANAME',
      'comments' => '',
      'help' => 'Doing Business As ',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-05-03 11:47:14',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => '',
    ),
    'Leadsindustry_c' => 
    array (
      'id' => 'Leadsindustry_c',
      'name' => 'industry_c',
      'label' => 'LBL_INDUSTRY',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-05-03 11:47:14',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'industry_dom',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => '',
    ),
    'Leadsmultilocation_c' => 
    array (
      'id' => 'Leadsmultilocation_c',
      'name' => 'multilocation_c',
      'label' => 'LBL_MULTILOCATION',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'NA',
      'date_modified' => '2014-05-03 11:47:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'multilocation_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => '',
    ),
    'Leadsmultitaxid_c' => 
    array (
      'id' => 'Leadsmultitaxid_c',
      'name' => 'multitaxid_c',
      'label' => 'LBL_MULTITAXID',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'Same',
      'date_modified' => '2014-05-03 11:47:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'multitaxid_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => '',
    ),
    'Leadsotherfirstname_c' => 
    array (
      'id' => 'Leadsotherfirstname_c',
      'name' => 'otherfirstname_c',
      'label' => 'LBL_OTHERFIRSTNAME',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-05-03 11:47:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => '',
    ),
    'Leadsotherlastname_c' => 
    array (
      'id' => 'Leadsotherlastname_c',
      'name' => 'otherlastname_c',
      'label' => 'LBL_OTHERLASTNAME',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-05-03 11:47:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => '',
    ),
    'Leadstaxid_c' => 
    array (
      'id' => 'Leadstaxid_c',
      'name' => 'taxid_c',
      'label' => 'LBL_TAXID',
      'comments' => NULL,
      'help' => '9 Digits TAX ID',
      'module' => 'Leads',
      'type' => 'int',
      'max_size' => '9',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-07-29 02:59:12',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '9999999',
      'ext2' => '999999999',
      'ext3' => NULL,
      'ext4' => NULL,
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/SearchFields.php',
      'to' => 'custom/modules/Leads/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Leads/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/detailviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/editviewdefs.php',
      'to' => 'custom/modules/Leads/metadata/editviewdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Leads/metadata/editviewdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/ru_ru.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/ru_ru.SecurityGroups.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/es_es.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/es_es.SecurityGroups.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/en_us.lead.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/en_us.lead.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/hu_hu.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/hu_hu.SecurityGroups.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/en_us.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/en_us.SecurityGroups.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/fr_FR.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/fr_FR.SecurityGroups.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/ge_ge.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/ge_ge.SecurityGroups.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/ua_ua.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/ua_ua.SecurityGroups.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/de_de.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/de_de.SecurityGroups.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/pt_br.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/pt_br.SecurityGroups.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/it_it.SecurityGroups.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/it_it.SecurityGroups.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Language/en_us.SendInfopack.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Language/en_us.SendInfopack.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_altsignertitle_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_altsignertitle_c.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_otherlastname_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_otherlastname_c.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_multitaxid_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_multitaxid_c.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_industry_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_industry_c.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/pass1_sendinfopack_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/pass1_sendinfopack_leads_Leads.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_dbaname_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_dbaname_c.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_claimfilingnumber_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_claimfilingnumber_c.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_companyname_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_companyname_c.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_taxid_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_taxid_c.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_otherfirstname_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_otherfirstname_c.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_cases_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_cases_c.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Vardefs/sugarfield_multilocation_c.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Vardefs/sugarfield_multilocation_c.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/Extension/modules/Leads/Ext/Layoutdefs/pass1_sendinfopack_leads_Leads.php',
      'to' => 'custom/Extension/modules/Leads/Ext/Layoutdefs/pass1_sendinfopack_leads_Leads.php',
    ),
  ),
);